### ISSUE TITLE
UI Error: TypeError: b.get is not a function

### ISSUE THREAD

**Issue by damnski** [davejab/nexus-repository-terraform#13]
* **What are you trying to do?**
Click through the UI within the terraform-proxy, and investigate an artifact, when the error pops up.
TypeError: b.get is not a function (http://private_ip:8080/static/rapture/nexus-repository-terraform-prod.js?_v=3.39.0-01&_e=OSS:1)

* **What feature or behavior is this required for?**
The nexus UI is throwing errors when clicking through the Browse --> terraform-proxy
Click on one of the cached resources: v1/providers/registry.terraform.io/hashicorp/aws/4.17.0
nexus version: 3.39.0-01
nexus-repository-terraform-0.0.3-bundle.kar

* **How could we solve this issue? (Not knowing is okay!)**
unknown

* **Anything else?**
nothing

Thank you,
-dkw

**Comment by davejab** [comment]
@damnski thanks for raising - this is fixed in [v0.0.4](https://github.com/davejab/nexus-repository-terraform/releases/tag/v0.0.4)

**Comment by damnski** [comment]
Hi @davejab,

Thanks for fixing.  I verified it works!  Awesome.  Thanks for including the LICENSE file as well for the bird's eye glance of the github license moniker.  Thanks for contributing.

Thank you,
Best,
-dkw
