### ISSUE TITLE
Allow double proxying

### ISSUE THREAD

**Issue by xaviou** [davejab/nexus-repository-terraform#25]
I'm trying to use two chained Nexus: let's call them small Nexus and big Nexus. Only big Nexus has Internet access.
My .terraformrc is: url = "https://mysmallnexus/repository/terraform-proxy/v1/providers"
In my small Nexus the terraform proxy remote storage is: https://mybignexus/repository/terraform-proxy/
In my big Nexus the terraform proxy remote storage is: https://registry.terraform.io

The request arriving at big Nexus is: https://mybignexus/repository/terraform-proxy/v1/providers/terraform-provider-openstack/openstack
(when it would only understand: https://mybignexus/repository/terraform-proxy/v1/providers/registry.terraform.io/terraform-provider-openstack/openstack)
At the end my client gets: 
```
Could not retrieve the list of available versions for provider
terraform-provider-openstack/openstack: failed to query provider mirror
https://mysmallnexus/repository/terraform-proxy/v1/providers/
for registry.terraform.io/terraform-provider-openstack/openstack: the request
failed after 2 attempts, please try again later: 500
```

**Comment by davejab** [comment]
Terraform registry and terraform mirrors are two completely different formats, this plugin is basically a translator for that so when you query the mirror from Terraform cli it is in the correct format. What is happening here is your small Nexus is trying to translate the already translated, if that makes sense. You are better converting your small Nexus repo to raw format and point it to your Terraform mirror in your big Nexus. Let me know if that works for you.

**Comment by xaviou** [comment]
Yes raw proxy works as a charm, thanks for the tip!
