### ISSUE TITLE
Could not retrieve the list of available versions for provider

### ISSUE THREAD

**Issue by eof151** [davejab/nexus-repository-terraform#3]
Hello!

After "terraform init" I recieved the error message:
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/random: provider registry.terraform.io/hashicorp/random was not found in any of the search locations
│
│   - provider mirror at https://mynexus.com/repository/terraform-proxy/

My ".terraformrc" file contains:
`provider_installation {
 network_mirror {
   url = "https://mynexus.com/repository/terraform-proxy/"
 }
}`

Is the problem with the mirror url or something else?

**Comment by davejab** [comment]
Hi @eof151 !

Could you please provide the following:

- Nexus version
- Nexus configuration
  - Remote storage URL 
- Terraform debug log (see [Debugging Terraform](https://www.terraform.io/internals/debugging))
- Terraform configuration file

Thanks!

**Comment by eof151** [comment]
Hello!
Thank you it's marvelous working!
