### ISSUE TITLE
Unable to view Terraform format after installing the bundle

### ISSUE THREAD

**Issue by gaeltardy-rlx** [davejab/nexus-repository-terraform#5]
Hi,

I currently try to install the plugin in our Sonatype Nexus Repository Manager PRO 3.38.1-01 but the format terraform is not visible when I want to create a new repo.
![image](https://user-images.githubusercontent.com/78016778/162684791-b882ae3b-a5f5-4c2e-877c-556b9f4fefa1.png)

I install by copying the release kar file (https://github.com/davejab/nexus-repository-terraform/releases/tag/v0.0.1) in the deploy folder.
The nexus log says that all has been installed:
```
2022-04-11 08:29:11,815+0200 INFO  [features-2-thread-1]  *SYSTEM org.sonatype.nexus.extender.NexusBundleTracker - ACTIVATING org.sonatype.nexus.plugins.nexus-repository-terraform [0.0.1]
2022-04-11 08:29:11,869+0200 INFO  [features-2-thread-1]  *SYSTEM org.sonatype.nexus.extender.NexusBundleTracker - ACTIVATED org.sonatype.nexus.plugins.nexus-repository-terraform [0.0.1]
```
When I checked the bundle installed, the bundle is Active:
![image](https://user-images.githubusercontent.com/78016778/162684723-bd599555-4c35-4ce2-a443-532f73afb959.png)

Do you have an idea?

Regards,
Gaël

**Comment by davejab** [comment]
Hi @gaeltardy-rlx !

Thanks for raising this issue.

Something changed in 3.38 that has broken custom repository formats. I will have a look in to this.

**Comment by davejab** [comment]
@gaeltardy-rlx 

Please try with v0.0.2:

https://github.com/davejab/nexus-repository-terraform/releases/tag/v0.0.2

**Comment by gaeltardy-rlx** [comment]
Thanks @davejab , my issue is solved
