### ISSUE TITLE
Error while installing carlpett/sops v0.6.2: failed to query provider mirror

### ISSUE THREAD

**Issue by eof151** [davejab/nexus-repository-terraform#9]
Hello!
Few days ago we recieved the error text after **terrafom init**:
`
Error: Failed to install provider
 
Error while installing carlpett/sops v0.6.2: failed to query provider mirror https://mynexus.domain/repository/terraform-proxy/v1/providers/ for
registry.terraform.io/carlpett/sops: the request failed after 2 attempts, please try again later: 500 Internal Server Error returned from
https://mynexus.domain/repository/terraform-proxy/v1/providers/registry.terraform.io/carlpett/sops/0.6.2.json`

But some days before it's worked perfectly.
And other providers (like AWS) now working good via your plugin.

Can you check working of this provider (carlpett/sops v0.6.2) on your machine via your plugin?

**Comment by davejab** [comment]
@eof151 thank for raising this, I have created a new release here: 

https://github.com/davejab/nexus-repository-terraform/releases/tag/v0.0.3

I'm unsure if this will work with Nexus versions older than 3.38. If you are running an older version let me know, I can publish a separate release for it.

**Comment by eof151** [comment]
Hello!  
I checked this fix, but it still don't work with nexus version 3.37.3
Did you tested it with this version?

**Comment by davejab** [comment]
I have created a patch release for Nexus versions older than 3.38 here:

https://github.com/davejab/nexus-repository-terraform/releases/tag/v0.0.1-1

I have tested locally and it is successfully fetching `v1/providers/registry.terraform.io/carlpett/sops/0.6.2.json`

![image](https://user-images.githubusercontent.com/13712138/163576685-626e6d88-30e3-4441-91c9-4539656584b1.png)
